# Sandbox cert-manager values
clusterIssuer:
  email: etknorr@gmail.com
  dns01:
    cloudflare:
      email: etknorr@gmail.com

# Certificate with both LKE and DO domains (shared wildcard)
certificate:
  name: sandbox-wildcard
  secretName: sandbox-wildcard-tls
  dnsNames:
    - sandbox.knorr.casa
    - "*.sandbox.knorr.casa"
    - sandbox-do.knorr.casa
    - "*.sandbox-do.knorr.casa"
