ingress:
  hostname: keycloak.sandbox-do.knorr.casa

service:
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: traefik-insecure-skip-verify@kubernetescrd

certificate:
  issuerName: letsencrypt-prod
  issuerKind: ClusterIssuer

realmImport:
  enabled: true
  domain: sandbox-do.knorr.casa
