{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretRef }}
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.clusterIssuer.dns01.cloudflare.email }}
            apiTokenSecretRef:
              name: {{ .Values.clusterIssuer.dns01.cloudflare.apiTokenSecretRef.name }}
              key: {{ .Values.clusterIssuer.dns01.cloudflare.apiTokenSecretRef.key }}
{{- end }}
