---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.20.2.1
    app.quarkus.io/vcs-uri: https://github.com/keycloak/keycloak.git
    app.quarkus.io/build-timestamp: 2025-08-20 - 10:19:29 +0000
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  name: keycloak-operator
